name: flutter_taller_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  image_picker_web: ^4.0.0
  file_picker: ^8.0.6
  url_launcher: ^6.0.0
  cached_network_image: ^3.2.0
  permission_handler: ^11.3.1
  speech_to_text: ^6.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
